import {createRouter,createWebHistory} from 'vue-router'

export default createRouter({
    history:createWebHistory(),
    routes:[
        {
            path:'/home',
            component:()=>import('@/pages/home/Home.vue'),
            meta:{
                title:'首页'
            }
        },
        {
            path:'/hospital',
            component:()=>import('@/pages/hospital/Hospital.vue'),
            meta:{
                title:'医院详情页'
            },
            children:[
                {
                    path:'register',
                    component:()=>import('@/pages/hospital/Register.vue'),
                    meta:{
                        title:'预约挂号'
                    }
                },
                {
                    path:'detail',
                    component:()=>import('@/pages/hospital/Detail.vue'),
                    meta:{
                        title:'医院介绍'
                    }
                },
                {
                    path:'notice',
                    component:()=>import('@/pages/hospital/Notice.vue'),
                    meta:{
                        title:'医院通告'
                    }
                },
                {
                    path:'close',
                    component:()=>import('@/pages/hospital/Close.vue'),
                    meta:{
                        title:'停诊通知'
                    }
                },
                {
                    path:'search',
                    component:()=>import('@/pages/hospital/Search.vue'),
                    meta:{
                        title:'相关查询'
                    }
                },
                {
                    path:'register_step1',
                    component:()=>import('@/pages/hospital/register_step1.vue'),
                    meta:{
                        title:'挂号第一步'
                    }
                }, 
                {
                    path:'register_step2',
                    component:()=>import('@/pages/hospital/register_step2.vue'),
                    meta:{
                        title:'挂号第二步'
                    }
                },        
        ]
        },
        {
            path:'/wxlogin',
            component:()=>import('@/pages/wxlogin.vue'),
            meta:{
                title:'微信登录页'
            }
        },
        {
            path:'/user',
            component:()=>import('@/pages/user/User.vue'),
            meta:{
                title:'用户首页'
            },
            children:[
                {
                    path:'certification',
                    component:()=>import('@/pages/user/Certification.vue'),
                    meta:{
                        title:'用户实名'
                    }
                },
                {
                    path:'order',
                    component:()=>import('@/pages/user/Order.vue'),
                    meta:{
                        title:'订单管理'
                    }
                },
                {
                    path:'feedback',
                    component:()=>import('@/pages/user/Feedback.vue'),
                    meta:{
                        title:'意见反馈'
                    }
                },
                {
                    path:'patient',
                    component:()=>import('@/pages/user/Patient.vue'),
                    meta:{
                        title:'就诊人管理'
                    }
                },
                {
                    path:'profile',
                    component:()=>import('@/pages/user/Profile.vue'),
                    meta:{
                        title:'账号信息'
                    }
                },
            ]
        },
        {
            path:'/',
            redirect:'/home'
        }
    ],
    //滚动行为：控制滚动条的位置
    scrollBehavior(){
        return{
            left:0,
            top:0
        }
    }

})